#!/bin/bash

set -e

branch=$1
command=$2

revisions=`git rev-list --reverse ${branch}`

for revision in $revisions; do
    git checkout --quiet $revision
    echo $command >&2
    eval $command
    git reset --hard
done
git checkout --quiet $branch
