#!/bin/bash

set -e

files=$@
output='playback.html'

source_file="${BASH_SOURCE[0]}"
while [ -h "$source_file" ]; do
  source_file="$(readlink "$source_file")";
done
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd -P "$(dirname "$source_file")" && pwd)"
unset source_file

js=`cat ${script_dir}/playback.js`
css=`cat ${script_dir}/playback.css`
htmlStart="<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='utf-8'>
    <title>Git Playback</title>

    <style type='text/css'>${css}</style>
    <link rel='stylesheet' href='http://yandex.st/highlightjs/6.2/styles/monokai.min.css' type='text/css'>
</head>
<body>
    <div id='playback'>
        <div class='container'>"

htmlEnd="</div>
    </div>

    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
    <script src='http://yandex.st/highlightjs/6.2/highlight.min.js'></script>
    <script type='text/javascript'>${js}</script>
    <script>
      jQuery(document).ready(function(){
          jQuery('#playback').playback();
          hljs.initHighlightingOnLoad();
      });
    </script>
</body>
</html>"

get_git_branch() {
  git branch 2>/dev/null|grep -e ^* | tr -d \*
}

foreach_git_revision() {
  branch=`get_git_branch`
  command=$1

  revisions=`git rev-list --reverse ${branch}`

  for revision in $revisions; do
      git checkout --quiet $revision
      eval $command
      git reset --hard
  done
  git checkout --quiet $branch
}

output_file() {
  no_files=true
  for file in $files
  do
    if [ -f $file ] && [ -s $file ]; then
      no_files=false
    fi
  done

  if ! $no_files; then
    echo '<div><ul>' >> $output
    for file in $files
    do
      echo '<li><pre><code>' >> $output
      if [ -f $file ]; then
        cat $file >> $output
      fi
      echo '</code></pre></li>' >> $output
    done
    echo '</ul></div>' >> $output
  fi
}

rm -f $output
echo $htmlStart >> $output
foreach_git_revision output_file
echo $htmlEnd >> $output
